version: '3.8'

services:
  undercover-game:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_WORD_API_ENDPOINT=${VITE_WORD_API_ENDPOINT:-http://localhost:3000/api/words}
    container_name: undercover-game
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.undercover.rule=Host(`undercover.umarsyariif.site`)"
      - "traefik.http.routers.undercover.entrypoints=websecure"
      - "traefik.http.routers.undercover.tls.certresolver=letsencrypt"
      - "traefik.http.services.undercover.loadbalancer.server.port=80"
    networks:
      - traefik-public

# Use external network - this assumes your existing Traefik is on a network called 'traefik-public'
# If your existing Traefik uses a different network name, replace 'traefik-public' with that name
networks:
  traefik-public:
    external: true 