version: '3.8'

services:
  undercover-game:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_WORD_API_ENDPOINT=${VITE_WORD_API_ENDPOINT:-http://localhost:3000/api/words}
    container_name: undercover-game
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=undercover.umarsyariif.site
      - LETSENCRYPT_HOST=undercover.umarsyariif.site
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    external:
      name: nginx-proxy 