################################################################
# Traefik Configuration for Undercover Game
################################################################

################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: false

################################################################
# Docker configuration
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public
  file:
    filename: /etc/traefik/dynamic_conf.yml

################################################################
# Let's Encrypt configuration
################################################################
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web 